editor/editor/urls.py
from django.contrib import admin
from django.urls import path,include
from main import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('main.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

editor/main/urls.py
from django.urls import path
from . import views

app_name = "main"   


urlpatterns = [
    path('',views.welcome,name='welcome'),
    path('mobile/', views.mobile, name='mobile'),
    path('category/<str:mid>/', views.category, name='category'),
    path('viewimage/<str:mid>/<str:cid>/',views.viewCategoryImage,name='viewimage'),
    path('editor/<str:mid>/<str:cid>/',views.editor,name='editor'),
    path('cropedimages/<str:mid>/<str:cid>/',views.cropedimages,name='cropedimages'),
    path('photocrop/<str:mid>/<str:cid>/',views.photocrop,name='photocrop'),
    path('photohighlight/<str:mid>/<str:cid>/',views.photoHighlight,name='photohighlight'),
    path('photocropsave/<str:mid>/<str:cid>/',views.photocropsave,name='photocropsave'),
    path('report/<str:mid>/',views.report,name='report')
]

editor/main/models.py
from django.db import models
# from django_quill.fields import QuillField
from ckeditor.fields import RichTextField

class Mobile(models.Model): 
    name = models.CharField(max_length=100, null=False, blank=False) 
    def __str__(self): 
        return self.name 
class Category(models.Model): 
    mobile = models.ForeignKey( 
        Mobile, on_delete=models.SET_NULL, null=True, blank=True) 
    name = models.CharField(max_length=100, null=False, blank=False) 
    # image = models.ImageField(null=False, blank=False) 
    # description = models.TextField() 
    def __str__(self): 
        return self.name 
class Photo(models.Model): 
    mobile = models.ForeignKey( 
        Mobile, on_delete=models.SET_NULL, null=True, blank=True) 
    category = models.ForeignKey( 
        Category, on_delete=models.SET_NULL, null=True, blank=True) 
    image = models.ImageField(null=False, blank=False) 
    cname = models.CharField(max_length=100, null=False, blank=False, default="samsung")
    def __str__(self): 
        return self.cname

class Photocrop(models.Model): 
    mobile = models.ForeignKey( 
        Mobile, on_delete=models.SET_NULL, null=True, blank=True) 
    category = models.ForeignKey( 
        Category, on_delete=models.SET_NULL, null=True, blank=True) 
    photo = models.ForeignKey( 
        Photo, on_delete=models.SET_NULL, null=True, blank=True) 
    cimage = models.ImageField(null=False, blank=False) 
    def __str__(self): 
        return str(self.id)

class Comments(models.Model):
    mobile = models.ForeignKey( 
        Mobile, on_delete=models.SET_NULL, null=True, blank=True) 
    category = models.ForeignKey( 
        Category, on_delete=models.SET_NULL, null=True, blank=True) 
    compList = models.CharField(max_length=100, null=False, blank=False,default="No Comments")
    name = models.CharField(max_length=100, null=False, blank=False)
    comment = RichTextField(blank=True,null=True)
    def __str__(self):
        return self.name

editor/main/forms.py
from django import forms
from .models import Comments
class CommentForm(forms.ModelForm):
	class Meta:
		model = Comments
		fields = ['name',  'comment']

		

editor/main/views.py
import imp
from inspect import getcomments
import re
from tempfile import tempdir
from urllib import request
from urllib.robotparser import RequestRate
from xml.etree.ElementTree import Comment
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .models import Mobile,Category,Photo,Comments,Photocrop
from .forms import CommentForm
from django.contrib import messages

# cropping modules
from django.core.files.storage import default_storage
from django.core.files.storage import FileSystemStorage
import os
import cv2
import json
import base64
from django.core import files
from ckeditor.fields import RichTextField

imgc = 0
photoc = ""
TEMP_PROFILE_IMAGE_NAME = "temp_profile_image.png"
data=[]
def welcome(request):
	return render(request,'main/welcome.html')
def mobile(request):
    # mob=Mobile.objects.filter(brand_id=id)
    mobile = Mobile.objects.all()
    # name=Brand.objects.get(id=id)
    context = {
        'mobile':mobile,
        } 
    return render(request, 'main/model.html',context)
def category(request,mid):
	i=mid
	name=Mobile.objects.get(id=mid)
	mob=Category.objects.filter(mobile_id=mid)
	cat = Category.objects.all()
	context={
        'mob': mob,
        'category':cat,
        'id':i,
        'name':name
    }
	return render(request, 'main/category.html',context)
def viewCategoryImage(request,mid,cid):
	global data
	name=Mobile.objects.get(id=mid)
	cate=Category.objects.get(id=cid)
	photo=Photo.objects.filter(category_id=cid,mobile_id=mid)	
	context={
		'mid':mid,
		'cid':cid,
		'name':name,
		'cate':cate,
        'photos':photo   
    }
	if request.method=="POST":
		data=request.POST.getlist("repid")
		if len(data)<=10:
			return redirect('main:editor',mid,cid)
		else:
			context['error']="Limit was Exceeded"
			return render(request,'main/view.html',context)

		# print(data)
		# if(len(data)>2):
		# 	context['error']="Limit was Exceeded"
		# 	return render(request,'main/view.html',context)
	
	return render(request, 'main/view.html',context) 
	# return redirect('main:editor',context)
	# return redirect('main:editor',mid,cid)
	# return context
# def editor(request,mid,cid):

def editor(request,mid,cid):
	global data	
	message=""	
	strData = ", ".join(str(v) for v in data)
	print(strData,"strdata++++++++++++++++++++++++")
	ph = []
	name=Mobile.objects.get(id=mid)
	cate=Category.objects.get(id=cid)

	for i in range(len(data)):
		ph.append(Photo.objects.get(category_id=cid,mobile_id=mid,id=int(data[i])))
	
	samsung=Photo.objects.filter(cname='samsung',category_id=cid,mobile_id=mid)
	
	if request.method == 'POST':
		n = request.POST.get('name')
		complist = request.POST.get('complist')
		cmt = request.POST.get('comment')
		res=Comments.objects.create(mobile=name,category=cate,name=n,comment=cmt, compList = complist)
		if res:
			message='Thank You for the comment'
		else:
			message='No Comment posted'
	form = CommentForm()
	cmmt = Comments.objects.filter(category_id=cid,mobile_id=mid)

	PH_IDs = []
	for eachObj in ph:
		PH_IDs.append(str(eachObj.id))
	print(list(map(int, mid)))
	# print(list(map(int, cid.split(" "))))
	# PH_ID_MID_CID = list(map(int, mid)) + list(map(int, cid)) + PH_IDs
	temp1=[]
	temp1.append(int(mid))
	temp2=[]
	temp2.append(int(cid))
	
	PH_ID_MID_CID = temp1 + temp2 + PH_IDs
	print(PH_ID_MID_CID)
	x=0
	print(x,"xxxxxxxxxx")

	context={
		'mid':mid,
		'cid':cid,
		'name':name,
		'cate':cate,
		'samsung': samsung,
        # 'photo1':photo1,
		# 'photo2':photo2,
		'photo':ph,
		# 'testing': ph,
		'form':form,
		"com_list": strData,	
		'cmmt':cmmt,
		"PH_ID_MID_CID":PH_ID_MID_CID,
		"message":message,
		'x':x
		# 'cp':cp
    }
	
	return render(request,'main/editor.html',context)

def cropedimages(request,mid,cid):
	cp = Photocrop.objects.filter(category_id=cid,mobile_id=mid)
	name=Mobile.objects.get(id=mid)
	cate=Category.objects.get(id=cid)
	context={
		'name':name,
		'cate':cate,
		"cp": cp
	}
	return render(request,'main/cropedimages.html',context)
def save_temp_profile_image_from_base64String(imageString, id):
	INCORRECT_PADDING_EXCEPTION = "Incorrect padding"
	try:
		if not os.path.exists(settings.TEMP):
			os.mkdir(settings.TEMP)
		if not os.path.exists(settings.TEMP + "\\" + str(id)):
			os.mkdir(settings.TEMP + "\\" + str(id))
		url = os.path.join(settings.TEMP + "\\" + str(id),TEMP_PROFILE_IMAGE_NAME)
		storage = FileSystemStorage(location=url)
		image = base64.b64decode(imageString)
		with storage.open('', 'wb+') as destination:
			destination.write(image)
			destination.close()
		return url
	except Exception as e:
		print("exception: " + str(e))
		# workaround for an issue I found
		if str(e) == INCORRECT_PADDING_EXCEPTION:
			imageString += "=" * ((4 - len(imageString) % 4) % 4)
			return save_temp_profile_image_from_base64String(imageString, id)
	return None
def photocrop(request,mid,cid,*args, **kwargs):
	global imgc
	global photoc
	imgc = request.POST.get('selectedimage')
	print("img",imgc)
	photoc=Photo.objects.filter(pk=imgc,category_id=cid,mobile_id=mid)
	print(photoc,"photoc")
	context={
		'mid':mid,
		'cid':cid,
        'photo':photoc 
    }
	urls,temp=[],[]
	if len(photoc)>0:
		for ph in photoc:
			urls.append(ph.image.url)
		temp=urls[0]
		print("urls[0]",urls[0])
	else:
		
		print("else")
	s=temp[1:]
	print(s)
	rimg = cv2.imread(str(s))
	print(rimg,"rimggggggg")
	with open(str(s), "rb") as img_file:
		imageString = base64.b64encode(img_file.read())			# print(my_string)
	url = save_temp_profile_image_from_base64String(imageString, imgc)
	print(url)
	if request.method == "POST":
			cropX = request.POST.get("x_axis")
			cropY = request.POST.get("y_axis")
			cropWidth = request.POST.get("img_width")
			cropHeight = request.POST.get("img_height")
			if cropX == None:
				cropX='0'
			if cropY == None:
				cropY='0'
			if cropWidth == None:
				cropWidth='0'
			if cropHeight == None:
				cropHeight='0'
			if float(cropX) < 0 or cropX==None:
				cropX = 0
			if float(cropY) < 0 or cropX==None: # There is a bug with cropperjs. y can be negative.
				cropY = 0
			x=int(float(str(cropX)))
			y=int(float(str(cropY)))
			h=int(float(str(cropHeight)))
			w=int(float(str(cropWidth)))
			print(x,y,w,h)
			# crop_img = rimg[y:y+h, x:x+w]
			# print("crop image",crop_img)
			# cv2.imwrite(url, crop_img)
		# res= Photocrop.objects.create(mobile=mid,category=cid,photo=img,cimage=)
		# crop_img = img[y:y+h, x:x+w]
		# cv2.imshow(url, crop_img)
		# cv2.waitKey(0)
		# crop_img = img[int(cropY):int(cropY)+int(cropHeight), int(cropX):int(cropX)+int(cropWidth)]
		# print(crop_img)
		# print(crop_img)
		# with open("my_image.jpg", "rb") as img_file:
		# 	my_string = base64.b64encode(img_file.read())
		# print(my_string)	

		# cv2.imwrite(url, crop_img)
	return render(request,'main/photocrop.html',context)
def photocropsave(request,mid,cid):
	global imgc
	global photoc
	print("pic",photoc)
	urls,temp=[],[]
	print(photoc)
	print("after photo")
	if len(photoc)>0:
		for ph in photoc:
			urls.append(ph.image.url)
		temp=urls[0]
		print("urls[0]",urls[0])
	else:
		
		print("else")
	s=temp[1:]
	print(s)
	rimg = cv2.imread(str(s))
	print(rimg)
	with open(str(s), "rb") as img_file:
		imageString = base64.b64encode(img_file.read())			# print(my_string)
	url = save_temp_profile_image_from_base64String(imageString, imgc)
	print(url)
	if request.method == "POST":
			cropX = request.POST.get("x_axis")
			cropY = request.POST.get("y_axis")
			cropWidth = request.POST.get("img_width")
			cropHeight = request.POST.get("img_height")
			if cropX == None:
				cropX='0'
			if cropY == None:
				cropY='0'
			if cropWidth == None:
				cropWidth='0'
			if cropHeight == None:
				cropHeight='0'
			if float(cropX) < 0 or cropX==None:
				cropX = 0
			if float(cropY) < 0 or cropX==None: # There is a bug with cropperjs. y can be negative.
				cropY = 0
			x=int(float(str(cropX)))
			y=int(float(str(cropY)))
			h=int(float(str(cropHeight)))
			w=int(float(str(cropWidth)))
			print(x,y,w,h)
			crop_img = rimg[y:y+h, x:x+w]
			print("crop image",crop_img)
			# cv2.imwrite(url, crop_img)
		# res= Photocrop.objects.create(mobile=mid,category=cid,photo=img,cimage=)
		# crop_img = img[y:y+h, x:x+w]
		# cv2.imshow(url, crop_img)
		# cv2.waitKey(0)
		# crop_img = img[int(cropY):int(cropY)+int(cropHeight), int(cropX):int(cropX)+int(cropWidth)]
		# print(crop_img)
		# print(crop_img)
		# with open("my_image.jpg", "rb") as img_file:
		# 	my_string = base64.b64encode(img_file.read())
		# print(my_string)	
			for i in photoc:
				print(i.id," instance")
			cv2.imwrite(url, crop_img)
			pc=Photocrop()
			for i in photoc:
				pc.photo= i
			mob=Mobile.objects.filter(pk=mid)
			cat=Category.objects.filter(pk=cid)
			print(mob)
			print(cat)
			for i in mob:
				pc.mobile=i
			
			for i in cat:
				pc.category=i
			
			# pc.mobile=mob
			# pc.category=cid
			pc.cimage= files.File(open(url,'rb'))
			pc.save()
			# Photocrop.cimage.save("",files.File(open(url,'rb')))
			context ={
		'cid':cid,
		'mid':mid
	}
			
	return redirect('main:cropedimages',mid,cid)
	return render(request,'croppedimages.html')
def photoHighlight(request,mid,cid):
	img = request.POST.get('selectedimage')
	print("img",imgc)
	photoc=Photo.objects.filter(pk=img,category_id=cid,mobile_id=mid)
	print(photoc,"photoc")
	context={	
		'mid':mid,
		'cid':cid,
        'photo':photoc 
    }
	return render(request,'main/photohighlight.html',context)
# def report(request,mid):
# 	data= Photo.objects.filter(mobile_id=mid)
# 	cats = Category.objects.filter(mobile_id =mid)

# 	print("Catergory =", cats)
# 	cmmt=[]
# 	for i in cats:
# 		print(i)
# 		c=Comments.objects.filter(mobile_id=mid,category_id=i.id)
# 		cmmt.append(c)
# 	print("Comments =", cmmt[0][0].comment)
# 	cmmt = ["Hi", "Hello"]
# 	l=[]
# 	for i in data:
# 		l.append(i.cname)
# 	context ={
# 		'cname':set(l),
# 		'data':data,
# 		'cats': cats,
# 		'cmmt':cmmt
# 	}
# 	return render(request,'main/report.html',context)

editor/main/templates/main/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'main/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="{% static 'cropperjs/dist/cropper.min.css' %}">
    {%if title%}
    <title>SE23 - {{title}}</title>
    {% else %}
    <title>SE23</title>
    {% endif %}
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.11/cropper.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.css">
</head>

<body>
    <div class="header"></div>
    <input type="checkbox" class="openSidebarMenu" id="openSidebarMenu">
    <label for="openSidebarMenu" class="sidebarIconToggle">
        <div class="spinner diagonal part-1"></div>
        <div class="spinner horizontal"></div>
        <div class="spinner diagonal part-2"></div>
    </label>
    <div id="sidebarMenu">
        <ul class="sidebarMenuInner">
            <li>Benchmarks <span>Samsung Prism</span></li>
            <li><a href="{% url 'main:welcome'%}" >Home</a></li>
            <li><a href="{% url 'main:mobile'%}" >Devices</a></li>
            <li><a href="#" >Images</a></li>
            <li><a href="#" >Activities</a></li>
            <li><a href="#" >Reports</a></li>
        </ul>
    </div>
    <div id='center' class="main center">
        {% block content %}{% endblock %}
    </div>
    
    <!-- <script src="{% static 'main/dist/wheel-zoom.min.js' %}"></script> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script> -->
    <script type="module" src="{% static 'cropperjs/dist/cropper.min.js' %}"></script>
</body>
<script src="https://kit.fontawesome.com/7716ff60e4.js" crossorigin="anonymous"></script>
</html>

editor/main/templates/main/editor.html
{% extends "main/base.html"%}
{% load static%}
{% load CompTag %}
{% comment %}
{% load crispy_forms_tags %}
{% endcomment %}
{% block content%}
{% if message %}
{{ message }}
{% endif %}

<div class="com_parent" >
    <div class="div21" style="width: 300px;">
        {% for ph in samsung %}
        <div class="selected-competitor">
            <div class="selected-competitor-first-half">
                <div class="selected-competitor-name">
                    <h5>{{ph.cname}}</h5>
                </div>
            </div>
            <div class="selected-competitor-second-half" style="overflow: scroll;">
                <div class="selected-competitor-img">
                    <img id="image0" src="{{ph.image.url}}" class="each-selected-competitor-img" alt="">
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    {% comment %}
    {{ testing }}
    {% for i in testing %}
    <img src="{{ i.image.url }}" alt="" width="50px">
    {% endfor %}
    {% endcomment %}

    <div class="div-scroll-horizontal" style="width:900px; display: inline-flex; overflow: scroll; scroll-direction: horizontal;">
        <div class="div22" >    
            {% for ph in photo %}
            <div class="selected-competitor">
                <div class="selected-competitor-first-half">
                    <div class="selected-competitor-name">
                        <h5>{{ph.cname}}</h5>
                    </div>
                </div>
                <div class="selected-competitor-second-half" style=" width:300px;overflow: scroll; scroll-direction: horizontal;">
                    <div class="selected-competitor-img" >
                        <img id="image{{ forloop.counter }}" src="{{ph.image.url}}" class="each-selected-competitor-img" alt="">
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    
    <!-- <div class="div23">
        {% for photo in photo2 %}
        <div class="selected-competitor">
            <div class="selected-competitor-first-half">
                <div class="selected-competitor-name">
                    <h5>{{photo.cname}}</h5>
                </div>
            </div>
            <div class="selected-competitor-second-half" style="overflow: scroll;">
                <div class="selected-competitor-img">
                    <img id="image3" src="{{photo.image.url}}" class="each-selected-competitor-img" alt="">
                </div>
            </div>
        </div>
        {% endfor %}
    </div> -->
    <div class="div23" >
        <div class="editor-second-container" style="width: 300px;">
            <div class="editor-framework" >
                <!-- <div class="highlighter">
                    <div id="highlighter">
                        <i class="fa-solid fa-pen-clip"></i> highlighter
                    </div>
                </div> -->
                <!-- <div class="icon-tools">
                    icon tools
                </div>
                <div class="shape-fill-func">
                    Shape Fill
                </div>
                <div class="shape-outline-func">
                    Shape Outline Fill
                </div>
                <div class="shape-effect-func">
                    Shape Effect
                </div> -->
                <form action="{% url 'main:photohighlight' mid cid %}" method="post">
                    {% csrf_token %} 
                    <select style="height: 40px; width: 100%;" class="form-select" id='selectedimage' name ='selectedimage'>
                        <option value="-1" default>Select image to highlight</option>
                        {% for ph in samsung %}
                        <option value="{{ph.id}}">{{ph.cname}}{{ph.id}}</option>
                        {% endfor %}
                        {% for ph in photo %}
                        <option value="{{ph.id}}">{{ph.cname}}{{ph.id}}</option>
                        {% endfor %}
                    </select><br>
                    <center>
                        <button type="submit" class="btn btn-outline-secondary mx-3 my-4"><i style="font-size: 40px;" class="fas fa-crop"></i> <br>highlight        
                        </button>
                    </center>
                    <br>
                </form>
                <form action="{% url 'main:photocrop' mid cid %}" method="post">
                    {% csrf_token %} 
                    <select style="height: 40px; width: 100%;" class="form-select " id='selectedimage' name ='selectedimage'>
                        <option value="-1" default>Select image to crop</option>
                        {% for ph in samsung %}
                        <option value="{{ph.id}}">{{ph.cname}}{{ph.id}}</option>
                        {% endfor %}
                        {% for ph in photo %}
                        <option value="{{ph.id}}">{{ph.cname}}{{ph.id}}</option>
                        {% endfor %}
                    </select><br><br>
                    <center>
                        <button type="submit" class="btn btn-outline-secondary mx-3 my-4"><i style="font-size: 40px;" class="fas fa-crop"></i><br>Crop
                        </button>
                    </center>
                </form>
                <!-- <div class="crop-selected-image-func">
                    <div id="crop-image">
                        <i class="fa-solid fa-crop-simple"></i>
                    </div>
                    <div class="crop-img-text">
                        Crop Image
                    </div>
                </div> -->
                <!-- <div class="ratio-info-func">
                    1 : 1
                </div> -->
                <div class="zoom-in-out-func">
                    <div class="zoom-out" id="zoomout" style="cursor: pointer;">
                        <div class="zoom-out-icon">
                            <i class="fa-solid fa-magnifying-glass-minus"></i>
                        </div>
                        <div class="zoom-out-text">
                            Zoom Out
                        </div>
                    </div>
                    <div class="zoom-in"  id="zoomin" style="cursor: pointer;">
                        <div class="zoom-in-icon">
                            <i class="fa-solid fa-magnifying-glass-plus"></i>
                        </div>
                        <div class="zoom-in-text">
                            Zoom In
                        </div>
                    </div>
                </div>
                <div class="add-result-func">
                    <div class="">
                        <button id="add-result" class="add-result-btn">Add Result</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% for i in PH_ID_MID_CID|getComments%}
{{ i|safe }}
{% endfor %}



<div id="myModal" class="modal">
  <div class="model-container">
    <div class="modal-content">
      <span id="close-model" class="close">&times;</span>
      <form action="" method="POST" class="comment-form">
        {{ form.media }}
        {% csrf_token %}
        <div class="div-name">
            <label for="">Name</label>
            {{form.name}}
        </div>
        <div class="div-name">
            <input type="text" name="complist" id="id_complist" value="{{ com_list }}" hidden>
        </div>
        <div class="div-comment">
            <label for="">Comment</label>    
            {{form.comment}}
        </div>
        <input type="submit" class="submit-form-comment" value="submit">
      </form>
    </div>
  </div>
</div>

<script>
    var modal = document.getElementById("myModal");
    var result_btn = document.getElementById("add-result");
    var span = document.getElementById("close-model");

    result_btn.onclick = function() {
        modal.style.display = "block";
    }

    span.onclick = function() {
        modal.style.display = "none";
    }

    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
    document.addEventListener('DOMContentLoaded', function () {

    var a=1.0

    document.getElementById("zoomin").addEventListener("click", () => {
        if(a<=5.0)
        {
            document.getElementById("image0").style.transform=`scale(${a})`
            {% for ph in photo %}
            document.getElementById("image{{ forloop.counter }}").style.transform=`scale(${a})`
            {% endfor %}
            a=a+0.5
        }
        console.log(a)
    });

    document.getElementById("zoomout").addEventListener("click", () => {
        if(a>1.0)
        {
            a-=0.5
            console.log(a);
            document.getElementById("image0").style.transform=`scale(${a})`

            {% for ph in photo %}
            document.getElementById("image{{ forloop.counter }}").style.transform=`scale(${a})`
            {% endfor %}
        }
    });
    });
</script>

{% endblock %}

editor/main/templates/main/model.html
{% extends "main/base.html"%}
{% block content%}
<div class="box-container">
  {%for n in mobile%}
  <div class="box" onclick="document.location='{% url 'main:category' n.id %}'">
      <div class="first-box-container">
          <a href="#" class="anchor_icon">
              <i class="fa-solid fa-folder"></i>
          </a>
      </div>
      <div class="second-box-container">
          <div class="folder-name">
              <h4 title="{{n}}">{{n}}</h4>
          </div>
          <div class="download-folder">
              <a href="{% url 'main:report' n.id %}" class="anchor_icon_2">
                  <i class="fa-solid fa-cloud-arrow-down"></i>
              </a>
          </div>
      </div>
  </div>
  {% endfor %}
</div>
<script>
    var boxes = document.getElementsByClassName("box");
    for (var i = 0; i < boxes.length; i++) {
        boxes[i].addEventListener("mouseover", function() {
            this.getElementsByClassName("anchor_icon")[0].innerHTML = "<i class='fa-solid fa-folder-open'></i>";
        });
        boxes[i].addEventListener("mouseout", function() {
            this.getElementsByClassName("anchor_icon")[0].innerHTML = "<i class='fa-solid fa-folder'></i>";
        });
    }
</script>

{% endblock %}

editor/main/templates/main/welcome.html
{% extends "main/base.html"%}
{% block content%}
<div class="container">
    Hi Welcome to Samsung
</div>
{% endblock %}